{
 "title": "ProjectMLOps_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accuracy - TweetEval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_accuracy{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy - YouTube",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_accuracy{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall TweetEval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_recall{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision YouTube",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_precision{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1 TweetEval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_f1{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1 YouTube",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_f1{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision TweetEval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_precision{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall YouTube",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_recall{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Accuracy over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "model_accuracy{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "model_accuracy{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "model_precision{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "model_precision{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1 Over  Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "model_f1{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "model_f1{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "model_recall{dataset=\"TweetEval\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "model_recall{dataset=\"YouTube\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}